// Optional local Postgres/WASM integration test. Pass a PGlite package directory and optional external vector package.
import { readFileSync } from 'node:fs';
import { pathToFileURL } from 'node:url';
import assert from 'node:assert/strict';
const packagePath = process.argv[2];
if (!packagePath) throw new Error('Usage: node tests/sql_test.mjs /path/to/pglite/package');
const { PGlite } = await import(pathToFileURL(`${packagePath}/dist/index.js`));
const vectorPath = process.argv[3] ? `${process.argv[3]}/dist/index.js` : `${packagePath}/dist/vector/index.js`;
const { vector } = await import(pathToFileURL(vectorPath));
const db = new PGlite({ extensions: { vector } });
await db.exec(`create role anon; create role authenticated; create role service_role bypassrls;
  create schema storage;
  create table storage.buckets(id text primary key, name text, public boolean, file_size_limit bigint, allowed_mime_types text[]);
  grant usage on schema public to anon, authenticated, service_role;`);
await db.exec(readFileSync(new URL('../supabase/migrations/001_party_face.sql', import.meta.url), 'utf8'));
await db.exec(readFileSync(new URL('../supabase/migrations/002_gallery.sql', import.meta.url), 'utf8'));
await db.exec(readFileSync(new URL('../supabase/migrations/003_stricter_matching.sql', import.meta.url), 'utf8'));
await db.exec(readFileSync(new URL('../supabase/migrations/004_facenet512.sql', import.meta.url), 'utf8'));
await db.exec(readFileSync(new URL('../supabase/migrations/005_person_groups.sql', import.meta.url), 'utf8'));
const model = 'face-api-0.22.2-ssd-landmark68-descriptor128-v1';
const ids = ['11111111-1111-4111-8111-111111111111', '22222222-2222-4222-8222-222222222222'];
for (let i = 0; i < 2; i++) await db.query(`insert into events(id,slug,title,token_hash,drive_folder_id,model_version,active) values($1,$2,'Event',$3,'folder',$4,true)`, [ids[i], `event-${i}`, 'a'.repeat(64), model]);
const descriptor = Array(128).fill(.1);
const newModel='facenet512-onnx-ssd68-align5-prewhiten-l2-v1', newEvent='33333333-3333-4333-8333-333333333333';
await db.query(`insert into events(id,slug,title,token_hash,drive_folder_id,model_version,threshold,active) values($1,'facenet-test','Test',$2,'folder',$3,.75,true)`,[newEvent,'b'.repeat(64),newModel]);
const newDescriptor=Array(512).fill(0);newDescriptor[0]=1;
await db.query(`select import_photo($1,'new-face','New','https://drive.google.com/file/d/x/view','thumb','fp',$2,$3::jsonb)`,[newEvent,newModel,JSON.stringify([{descriptor:newDescriptor,box:{}}])]);
assert.equal((await db.query(`select match_photos($1,$2::extensions.vector) as result`,[newEvent,JSON.stringify(newDescriptor)])).rows[0].result.total,1);
await assert.rejects(()=>db.query(`select match_photos($1,$2::extensions.vector)`,[newEvent,JSON.stringify(descriptor)]));
await assert.rejects(()=>db.query(`select import_photo($1,'bad','Bad','url','thumb','fp',$2,$3::jsonb)`,[newEvent,newModel,JSON.stringify([{descriptor:Array(512).fill(.1),box:{}}])]));
const faces = JSON.stringify([{ descriptor, box: { x: .1, y: .1, width: .2, height: .2 } }, { descriptor, box: { x: .4, y: .4, width: .2, height: .2 } }]);
async function importPhoto(event, file, vectors = faces, version = model) {
  return db.query(`select import_photo($1,$2,$2,'https://drive.google.com/file/d/photo/view',$3,'fingerprint',$4,$5::jsonb) as id`, [event, file, `${event}/${file}.jpg`, version, vectors]);
}
for (let i = 0; i < 40; i++) await importPhoto(ids[0], `photo-${i}`);
await importPhoto(ids[1], 'other-event-photo');
const match = async offset => (await db.query(`select match_photos($1,$2::extensions.vector,$3) as result`, [ids[0], JSON.stringify(descriptor), offset])).rows[0].result;
const page1 = await match(0), page2 = await match(24);
assert.equal(page1.total, 40); assert.equal(page1.photos.length, 24); assert.equal(page2.photos.length, 16);
assert.equal(new Set([...page1.photos, ...page2.photos].map(p => p.id)).size, 40);
assert.equal(page1.photos.some(p => p.name === 'other-event-photo'), false);
await db.query(`select import_photo($1,'unindexed','no-face.jpg','https://drive.google.com/file/d/x/view','thumb.jpg','fp',$2,'[]'::jsonb,'活动',false)`, [ids[0], model]);
await db.query(`update photos set album_path='工作组' where event_id=$1 and drive_file_id='photo-0'`, [ids[0]]);
const browse = async (event, album = null, query = '', offset = 0) => (await db.query(`select browse_photos($1,$2,$3,$4) as result`, [event, album, query, offset])).rows[0].result;
const galleryPage1 = await browse(ids[0]), galleryPage2 = await browse(ids[0], null, '', 24);
assert.equal(galleryPage1.total, 41); assert.equal(galleryPage1.photos.length, 24); assert.equal(galleryPage2.photos.length, 17);
assert.equal(new Set([...galleryPage1.photos, ...galleryPage2.photos].map(p => p.id)).size, 41);
assert.equal((await browse(ids[0], '活动')).photos[0].name, 'no-face.jpg');
assert.equal((await browse(ids[0], '工作组')).total, 1);
assert.equal((await browse(ids[0], null, 'no-face')).total, 1);
assert.equal((await browse(ids[0], null, '%')).total, 0);
assert.equal((await browse(ids[0], 'unknown')).total, 0);
assert.equal((await match(0)).total, 40);
// A synthetic distance of .45 must be rejected at .42 but accepted at .50.
// This checks cutoff behavior, not recognition accuracy on real people.
const borderline = [...descriptor]; borderline[0] += .45;
await importPhoto(ids[0], 'borderline', JSON.stringify([{ descriptor: borderline, box: {} }]));
assert.equal((await match(0)).total, 40);
await db.query('update events set threshold=.50 where id=$1', [ids[0]]);
assert.equal((await match(0)).total, 41);
await db.query('update events set threshold=.42 where id=$1', [ids[0]]);
await db.query('delete from photos where event_id=$1 and drive_file_id=$2', [ids[0], 'borderline']);
const summary = (await db.query('select gallery_summary($1) as summary', [ids[0]])).rows[0].summary;
assert.equal(summary.photo_count, 41); assert.equal(summary.indexed_photo_count, 40);
await assert.rejects(() => importPhoto(ids[0], 'photo-0', JSON.stringify([{ descriptor: [1], box: {} }])));
assert.equal((await db.query('select count(*)::int as count from faces f join photos p on p.id=f.photo_id where p.drive_file_id=$1', ['photo-0'])).rows[0].count, 2);
await importPhoto(ids[0], 'photo-0', JSON.stringify([{ descriptor, box: {} }]));
assert.equal((await db.query('select count(*)::int as count from faces f join photos p on p.id=f.photo_id where p.drive_file_id=$1', ['photo-0'])).rows[0].count, 1);
await assert.rejects(() => importPhoto(ids[0], 'bad-model', faces, 'wrong'));
await db.exec('set role anon');
await assert.rejects(() => db.query('select * from faces'));
await assert.rejects(() => match(0));
await assert.rejects(() => browse(ids[0]));
await db.exec('reset role');
await db.query('update events set active=false where id=$1', [ids[0]]);
assert.equal((await match(0)).total, 0);
assert.equal((await browse(ids[0])).total, 0);
await db.query('update events set active=true, expires_at=now()-interval \'1 day\' where id=$1', [ids[0]]);
assert.equal((await match(0)).total, 0);
assert.equal((await browse(ids[0])).total, 0);
const client = 'b'.repeat(64);
for (let i = 0; i < 300; i++) assert.equal((await db.query(`select consume_budget($1,$2,'search') as permit`, [ids[0], client])).rows[0].permit, true);
assert.equal((await db.query(`select consume_budget($1,$2,'search') as permit`, [ids[0], client])).rows[0].permit, false);
assert.equal((await db.query(`select consume_budget($1,$2,'browse') as permit`, [ids[0], 'c'.repeat(64)])).rows[0].permit, true);
assert.equal((await db.query(`select public from storage.buckets where id='event-thumbnails'`)).rows[0].public, false);
// A reviewed group expands a front-face match to its manually linked side-face photo.
const unit=angle=>[Math.cos(angle),Math.sin(angle),...Array(510).fill(0)];
for(const [name,angle] of [['side',1.2],['other-person',2],['pending-person',-.8]])
  await db.query(`select import_photo($1,$2,$2,'url','thumb','fp',$3,$4::jsonb)`,[newEvent,name,newModel,JSON.stringify([{descriptor:unit(angle),box:{}}])]);
const imported=(await db.query(`select f.id::text id,p.drive_file_id file from faces f join photos p on p.id=f.photo_id where f.event_id=$1`,[newEvent])).rows;
const byFile=file=>imported.find(f=>f.file===file).id;
const signature=(await db.query('select person_index_signature($1) signature',[newEvent])).rows[0].signature;
const reviewed=[{name:'A',reviewed:true,faces:[byFile('new-face'),byFile('side')]},{name:'B',reviewed:true,faces:[byFile('other-person')]},{name:'pending',reviewed:false,faces:[byFile('pending-person')]}];
const saveGroups=async groups=>(await db.query('select save_person_groups($1,$2::jsonb,$3) result',[newEvent,JSON.stringify(groups),signature])).rows[0].result.revision;
const groupMatch=async angle=>(await db.query('select match_person_groups($1,$2::extensions.vector) result',[newEvent,JSON.stringify(unit(angle))])).rows[0].result;
const revision=await saveGroups(reviewed);
assert.equal((await db.query('select published_group_revision from events where id=$1',[newEvent])).rows[0].published_group_revision,null,'saving a draft does not publish');
await db.query('select publish_person_groups($1,$2)',[newEvent,revision]);
assert.equal((await groupMatch(0)).total,2,'front match returns linked side photo too');
assert.equal((await groupMatch(2)).total,1);
assert.equal((await groupMatch(-.8)).total,0,'unreviewed group never returns photos');
assert.equal((await groupMatch(1.6)).total,0,'similar scores for different groups are ambiguous');
const draft=await saveGroups(reviewed.map(g=>({...g,reviewed:false})));
await assert.rejects(()=>db.query('select publish_person_groups($1,$2)',[newEvent,draft]));
assert.equal((await groupMatch(0)).total,2,'unpublished editing does not change live snapshot');
await assert.rejects(()=>saveGroups(reviewed.slice(0,1)),'all indexed faces must be assigned');
const foreign=(await db.query('select id::text id from faces where event_id=$1 limit 1',[ids[1]])).rows[0].id;
await assert.rejects(()=>saveGroups([...reviewed,{name:'foreign',reviewed:true,faces:[foreign]}]));
await assert.rejects(()=>db.query('select publish_person_groups($1,$2)',[ids[0],revision]));
await assert.rejects(()=>db.query('select match_person_groups($1,$2::extensions.vector)',[newEvent,JSON.stringify(descriptor)]));
await db.exec('set role anon');
await assert.rejects(()=>db.query('select * from person_groups'));
await assert.rejects(()=>groupMatch(0));
await db.exec('reset role');
await db.query('update events set active=false where id=$1',[newEvent]);assert.equal((await groupMatch(0)).total,0);
await db.query('update events set active=true where id=$1',[newEvent]);
await db.query(`select import_photo($1,'side','side','url','thumb','changed',$2,$3::jsonb)`,[newEvent,newModel,JSON.stringify([{descriptor:unit(1.2),box:{}}])]);
await assert.rejects(()=>groupMatch(0),'reimport invalidates published grouping');
await assert.rejects(()=>db.query('select publish_person_groups($1,$2)',[newEvent,revision]));
await db.close();
console.log('Postgres integration passed: all migrations, stricter matching cutoff, browse of unindexed photos, album/filename filters, full pagination, event isolation, rollback, visitor access denial, expiry and rate limits.');
